version: 1.0.{build}
image: Visual Studio 2017
configuration: Release
environment:
  QTDIR: D:\qt12\5.12.3\msvc2017_64
  PATH: '%PATH%;D:\qt12\5.12.3\msvc2017_64\bin;C:\Program Files\Git\bin;D:\qt12\Tools\QtCreator\bin'
install:
- cmd: >-
    git submodule update --init --recursive

    call "D:\visual studio\VC\Auxiliary\Build\vcvarsall.bat" x86_amd64

    call %QTDIR%\bin\qtenv2.bat
before_build:
- cmd: >-
    cd %APPVEYOR_BUILD_FOLDER%\hrm\src

    qmake human_resource_machine.pro
build:
  verbosity: minimal
after_build:
- cmd: >-
    jom qmake_all

    jom.exe -f Makefile.Release
artifacts:
- path: '\hrm\src\release'
  name: human_resource_machine
  type: WebDeployPackage
